services:
#  zookeeper:
#    image: zookeeper
#    networks:
#      - fospay_network
#    ports:
#      - 12181:2181
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#      - ZOO_TLS_CLIENT_AUTH=none
#      - ZOO_TLS_QUORUM_CLIENT_AUTH=none
#
#  kafka:
#    image: bitnami/kafka
#    networks:
#      - fospay_network
#    ports:
#      - 19092:9092
#    environment:
#      - KAFKA_CFG_NODE_ID=1
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:12181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CFG_LISTENERS=LC://kafka:29092,LX://kafka:19092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:19092
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LC:PLAINTEXT,LX:PLAINTEXT
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LC
#    depends_on:
#      - zookeeper
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui
#    networks:
#      - fospay_network
#    ports:
#      - 18989:8080
#    restart: always
#    depends_on:
#      - zookeeper
#      - kafka
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:12181

  mysql:
    image: mysql
    networks:
      - fospay_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - 13306:3306
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  membership-service:
    image: fospay-membership-service:1.0.0
    networks:
      - fospay_network
    ports:
      - 18080:18080
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fospay?useSSL=false&allowPublicKeyRetrieval=true

  banking-service:
    image: fospay-banking-service:1.0.0
    networks:
      - fospay_network
    ports:
      - 18081:18081
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fospay?useSSL=false&allowPublicKeyRetrieval=true


networks:
  fospay_network:
    driver: bridge