services:
  axon-server:
    image: axoniq/axonserver:latest-jdk-17
    networks:
      - fospay_network
    ports:
      - "18024:8024"
      - "18124:8124"
    volumes:
      - axonserver-data:/axonserver/data
      - axonserver-events:/axonserver/events
      - axonserver-config:/axonserver/config:ro
      - axonserver-plugin:/axonserver/plugins

  zookeeper:
    image: zookeeper
    networks:
      - fospay_network
    ports:
      - 12181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none

  kafka:
    image: bitnami/kafka
    networks:
      - fospay_network
    ports:
      - 19092:9092
      - 19093:9093
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=LC://kafka:9093,LX://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=LC://kafka:9093,LX://${DOCKER_HOST_IP:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LC:PLAINTEXT,LX:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LC
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    networks:
      - fospay_network
    ports:
      - 18989:8080
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  mysql:
    image: mysql
    networks:
      - fospay_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - 13306:3306
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  membership-service:
    image: fospay-membership-service:1.0.0
    networks:
      - fospay_network
    ports:
      - 18080:18080
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fospay?useSSL=false&allowPublicKeyRetrieval=true
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:9093
      - AXON_AXONSERVER_SERVERS=axon-server:8124

  banking-service:
    image: fospay-banking-service:1.0.0
    networks:
      - fospay_network
    ports:
      - 18081:18081
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fospay?useSSL=false&allowPublicKeyRetrieval=true
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:9093
      - SERVICE_MEMBERSHIP_URL=http://membership-service:18080
      - AXON_AXONSERVER_SERVERS=axon-server:8124

  money-service:
    image: fospay-money-service:1.0.0
    networks:
      - fospay_network
    ports:
      - 18082:18082
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fospay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:9093
      - SERVICE_MEMBERSHIP_URL=http://membership-service:18080
      - SERVICE_BANKING_URL=http://banking-service:18081
      - AXON_AXONSERVER_SERVERS=axon-server:8124

  logging-consumer:
    image: fospay-logging-consumer:1.0.0
    networks:
      - fospay_network
    depends_on:
      - kafka
      - zookeeper
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - AXON_AXONSERVER_SERVERS=axon-server:8124

  task-producer:
    image: fospay-task-consumer:1.0.0
    networks:
      - fospay_network
    depends_on:
      - kafka
      - zookeeper
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - AXON_AXONSERVER_SERVERS=axon-server:8124

  remittance-service:
    image: fospay-remittance-service:1.0.0
    networks:
      - fospay_network
    ports:
      - 18083:18083
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fospay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:9093
      - SERVICE_MEMBERSHIP_URL=http://membership-service:18080
      - SERVICE_BANKING_URL=http://banking-service:18081
      - SERVICE_MONEY_URL=http://money-service:18082
      - AXON_AXONSERVER_SERVERS=axon-server:8124

  payment-service:
    image: fospay-payment-service:1.0.0
    networks:
      - fospay_network
    ports:
      - 18084:18084
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fospay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:9093
      - SERVICE_MEMBERSHIP_URL=http://membership-service:18080
      - SERVICE_BANKING_URL=http://banking-service:18081
      - AXON_AXONSERVER_SERVERS=axon-server:8124

networks:
  fospay_network:
    driver: bridge

volumes:
  axonserver-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/axon-server-se/data
  axonserver-events:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/axon-server-se/events
  axonserver-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/axon-server-se/config
  axonserver-plugin:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/axon-server-se/plugin